import { Button, VerticalBox, LineEdit } from "std-widgets.slint";





export component AppWindow inherits Window {

   in property <string> results:"";
   property <bool> opnencurtain;
    callback divide-income(string);

    background: #1b3251;
GridLayout {
    padding: 50px;
    spacing: 25px;
                Row{
                    Text{
                        text:"Enter Total Icome";
                        horizontal-alignment: center;
                        font-size: 24px;
                        font-weight: 900;
                        
                        }
                    }

                Row{
                    income:= LineEdit {
                        horizontal-alignment: center;
                        placeholder-text: "Enter Your Number";
                        font-size: 14px;     
                        height: 35px;
             

                    }

                }
                Row{
                    Button {
                        text: "calculate";
                        primary:true;
                        height: 35px;
                        clicked => {
                            root.opnencurtain=!root.opnencurtain;
                            divide-income(income.text)}
                    }
                  }
                Row{
                    VerticalBox {
                        Rectangle {
                            height: 100px;
                            background: #f2f2f2;
                            Text {
                                color: black;
                                font-size: 16px;
                                font-weight: 500;
                                text: root.results;
                            }
                            //left rectangle

                            Rectangle {
                                background: #333333;
                                x: 0;
                                width: opnencurtain ? 0px : parent.width/2;
                                height: parent.height;
                                animate width {
                                     duration: 250ms;easing: ease-in;
                                }
                            }

                            //right rectangle
                            Rectangle {
                                background: #333333;
                                x: opnencurtain?parent.width : parent.width/2;
                                height: parent.height;
                                animate width {
                                     duration: 250ms;easing: ease-in;
                                }
                                animate x {
                                    duration: 250ms;easing: ease-in;
                               }
                            }

                        }
                    }
                }
        }
    }
